"""Build one `_SIMULATED` UPI Autopay failure envelope per reason Razorpay documents,
and render docs/taxonomy.md §12's table from the mapping.

    python tools/make_upi_stubs.py <create-subsequent-payments.md> <errors-list.md>
    python tools/make_upi_stubs.py table

Both arguments are copies of Razorpay's documentation, each checked against the
SHA-256 registered in docs/EVALUATION.md §10, 2026-09-15, so any copy with the
same bytes rebuilds the same files and nothing else can:

  - *Create Subsequent Payments* (UPI), from
    https://razorpay.com/docs/api/payments/recurring-payments/upi/create-subsequent-payments.md
    — its "Error Response Parameters" section gives the 61 reasons, each with a
    description and next steps.
  - *List of Errors*, from
    https://razorpay.com/docs/build/llm-docs/errors/payments/list.md — which
    files 19 of those reasons under "Bad Request Errors" or "Gateway Errors",
    the only place any of them is given an `error_code`.

**Only what the pages say.** The reason and its description are verbatim. The
code is set where the list files the reason, and left null where it does not.
`error_source` and `error_step` are null in every file: Razorpay documents the
values UPI can take for both, and pairs neither with any reason, so a value
here would be a pairing nobody documented (docs/EVALUATION.md §10, 2026-09-15).

**The envelope is the one real non-card capture.** `27af45` is a netbanking
payment captured live; each stub is that envelope with `method` set to `upi`,
the netbanking `bank` code cleared because it names the bank a netbanking
payment used, and the error fields replaced. `vpa` stays null: no payer address
is documented. Named `SIMULATED__upi_autopay__<reason>.json`, outside the
`SIMULATED__payment_failed__*` pattern every card reader globs, so no card
table ever indexes one.
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
BASE = REPO_ROOT / "data" / "observed_payloads" / "payment_failed__payment_failed__27af45.json"
OUT = REPO_ROOT / "data" / "stubbed_payloads"
PREFIX = "SIMULATED__upi_autopay__"

SUBSEQUENT_SHA256 = "6c26636bafa1b66801ecae4b44b8250a354d5269d3a3c2ee6baf0adb972d1bfe"
LIST_SHA256 = "5e6fb5795996400ddd55938c60b217dbe403995af45669b12ac02a5b51c4281d"
CODES = {"Bad Request Errors": "BAD_REQUEST_ERROR", "Gateway Errors": "GATEWAY_ERROR"}

NOTE = (
    "Simulated. A UPI Autopay failure as Razorpay documents it: reason and description "
    "verbatim from 'Create Subsequent Payments' (UPI), Error Response Parameters, markdown "
    "source SHA-256 {subsequent}; error_code from Razorpay's 'List of Errors' (SHA-256 "
    "{listing}) where it files the reason, else null; error_source and error_step null "
    "because no Razorpay page pairs them with a UPI reason. Envelope: the observed netbanking "
    "capture {base}, with method set to upi and its netbanking bank code cleared. Built by "
    "tools/make_upi_stubs.py. Documented next steps: {steps}"
)


def _checked(path: pathlib.Path, sha256: str) -> str:
    data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != sha256:
        raise SystemExit(f"{path}: SHA-256 {digest}, expected {sha256} — not the registered document")
    return data.decode()


def reasons(markdown: str) -> dict[str, list[tuple[str, str]]]:
    """reason -> [(description, next steps), ...], one pair per documented variant."""
    section = markdown[
        markdown.index("possible errors you may face while creating a Recurring Payment"):
        markdown.index("## 3.3.")
    ]
    blocks = re.split(r'^  <Accordion title="([a-z_]+)">', section, flags=re.M)[1:]
    out: dict[str, list[tuple[str, str]]] = {}
    for reason, body in zip(blocks[0::2], blocks[1::2]):
        descriptions = re.findall(r"\*\*Description\*\*: (.+)", body)
        steps = re.findall(r"\*\*Next Steps\*\*: (.+)", body)
        out[reason] = [(d.strip(), s.strip()) for d, s in zip(descriptions, steps)]
    return out


def codes(listing: str) -> dict[str, str]:
    """reason -> error_code, for the reasons the list files under a code heading."""
    out: dict[str, str] = {}
    heading = None
    for line in listing.splitlines():
        match = re.match(r"^## (.+)$", line)
        if match:
            heading = match.group(1)
            continue
        row = re.match(r"^([a-z_]+) \|", line)
        if row and heading in CODES:
            out[row.group(1)] = CODES[heading]
    return out


TAXONOMY = REPO_ROOT / "docs" / "taxonomy.md"
TABLE_START = "<!-- upi-table:start — generated by `python tools/make_upi_stubs.py table`; do not edit -->"
TABLE_END = "<!-- upi-table:end -->"


def render_table() -> str:
    """§12's table: every reason under its outcome, with the description its
    stub carries verbatim, the code where Razorpay files one, and the why."""
    sys.path.insert(0, str(REPO_ROOT))
    from vasool.diagnosis.npci import Unmapped
    from vasool.diagnosis.razorpay_upi import MAPPINGS
    from vasool.diagnosis.taxonomy import FailureClass

    stubs = {}
    for path in sorted(OUT.glob(f"{PREFIX}*.json")):
        entity = json.loads(path.read_text())["body"]["payload"]["payment"]["entity"]
        stubs[entity["error_reason"]] = entity
    lines = [TABLE_START]
    for outcome in [*FailureClass, *Unmapped]:
        rows = [m for m in MAPPINGS if m.outcome is outcome]
        if not rows:
            continue
        label = f"`{outcome.value}`" if isinstance(outcome, FailureClass) else f"Unmapped — `{outcome.value}`"
        lines += ["", f"#### {label} ({len(rows)})", "",
                  "| Reason | Razorpay's description | Code | Why |", "|---|---|---|---|"]
        for m in rows:
            entity = stubs[m.reason]
            description = entity["error_description"].replace("|", "\\|")
            lines.append(f"| `{m.reason}` | {description} | {entity['error_code'] or '—'} | {m.why} |")
    lines += ["", TABLE_END]
    return "\n".join(lines)


def write_table() -> None:
    text = TAXONOMY.read_text()
    if TABLE_START not in text or TABLE_END not in text:
        raise SystemExit("error: docs/taxonomy.md has no upi-table markers")
    head, rest = text.split(TABLE_START, 1)
    _, tail = rest.split(TABLE_END, 1)
    TAXONOMY.write_text(head + render_table() + tail)
    print("rewrote docs/taxonomy.md §12's table")


def main(argv: list[str]) -> int:
    if argv == ["table"]:
        write_table()
        return 0
    if len(argv) != 2:
        print(__doc__)
        return 2
    documented = reasons(_checked(pathlib.Path(argv[0]), SUBSEQUENT_SHA256))
    filed = codes(_checked(pathlib.Path(argv[1]), LIST_SHA256))
    template = json.loads(BASE.read_text())

    for stale in OUT.glob(f"{PREFIX}*.json"):
        stale.unlink()
    for reason, variants in sorted(documented.items()):
        stub = json.loads(json.dumps(template))
        stub["_SIMULATED"] = True
        stub["_source_note"] = NOTE.format(
            subsequent=SUBSEQUENT_SHA256[:12],
            listing=LIST_SHA256[:12],
            base=BASE.name,
            steps=" | ".join(steps for _, steps in variants),
        )
        entity = stub["body"]["payload"]["payment"]["entity"]
        entity["method"] = "upi"
        entity["bank"] = None
        entity["error_reason"] = reason
        entity["error_description"] = variants[0][0]
        entity["error_code"] = filed.get(reason)
        entity["error_source"] = None
        entity["error_step"] = None
        (OUT / f"{PREFIX}{reason}.json").write_text(json.dumps(stub, indent=2, ensure_ascii=False) + "\n")
    print(f"{len(documented)} UPI Autopay stubs written to {OUT.relative_to(REPO_ROOT)}/, "
          f"{sum(r in filed for r in documented)} with a documented error_code")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
